# Generated by Django 4.1.5 on 2023-01-12 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serNumM', models.CharField(max_length=30)),
                ('serNumE', models.CharField(max_length=30)),
                ('serNumT', models.CharField(max_length=30)),
                ('serNumDA', models.CharField(max_length=30)),
                ('serNumSA', models.CharField(max_length=30)),
                ('NumSupContract', models.CharField(max_length=30)),
                ('dateShipmentFactory', models.DateField()),
                ('consignee', models.CharField(max_length=30)),
                ('addressOperation', models.CharField(max_length=128)),
                ('equipment', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ModelDriveAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelSteeringAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('workOrder', models.CharField(max_length=30)),
                ('dateWorkOrder', models.DateField()),
                ('machine', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.machine')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.servicecompany')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.typemaintenance')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='modelDA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.modeldriveaxle'),
        ),
        migrations.AddField(
            model_name='machine',
            name='modelE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.modelengine'),
        ),
        migrations.AddField(
            model_name='machine',
            name='modelM',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.modelmachine'),
        ),
        migrations.AddField(
            model_name='machine',
            name='modelSA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.modelsteeringaxle'),
        ),
        migrations.AddField(
            model_name='machine',
            name='modelT',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.modeltransmission'),
        ),
        migrations.AddField(
            model_name='machine',
            name='userClient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machine',
            name='userService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.servicecompany'),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRejection', models.DateField()),
                ('failDescription', models.CharField(max_length=128)),
                ('spareParts', models.CharField(max_length=128)),
                ('dateRecovery', models.DateField()),
                ('downtime', models.PositiveIntegerField(blank=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.machine')),
                ('recMethod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.recoverymethod')),
                ('typeFailure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.typefailure')),
            ],
        ),
    ]
