# Generated by Django 4.1.5 on 2023-01-18 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysilantapp', '0002_servicecompany_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSilant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryType', models.CharField(choices=[('MG', 'Менеджер'), ('CL', 'Клиент'), ('SK', 'Сервисная компания')], max_length=2)),
                ('silUser', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
