# Generated by Django 4.1.5 on 2023-01-19 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysilantapp', '0004_alter_servicecompany_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='userClient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.usersilant'),
        ),
    ]
