# Generated by Django 4.1.5 on 2023-01-19 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysilantapp', '0005_alter_machine_userclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='userClient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machine',
            name='userService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service', to=settings.AUTH_USER_MODEL),
        ),
    ]
