# Generated by Django 4.1.5 on 2023-01-20 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysilantapp', '0006_alter_machine_userclient_alter_machine_userservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='userService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service', to='mysilantapp.servicecompany'),
        ),
    ]
