# Generated by Django 4.1.5 on 2023-01-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysilantapp', '0007_alter_machine_userservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mysilantapp.typemaintenance'),
        ),
    ]
