# Generated by Django 4.1.5 on 2023-01-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysilantapp', '0008_alter_maintenance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='operTime',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
