# Generated by Django 4.1.5 on 2023-01-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysilantapp', '0011_alter_machine_userclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersilant',
            name='categoryType',
            field=models.CharField(choices=[('Менеджер', 'Менеджер'), ('Клиент', 'Клиент'), ('Сервисная компания', 'Сервисная компания')], max_length=18),
        ),
    ]
