# Generated by Django 4.1.5 on 2023-01-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysilantapp', '0012_alter_usersilant_categorytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersilant',
            name='categoryType',
            field=models.CharField(choices=[('MG', 'Менеджер'), ('CL', 'Клиент'), ('SK', 'Сервисная компания')], max_length=2),
        ),
    ]
