# Generated by Django 4.1.5 on 2023-01-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysilantapp', '0014_alter_modeldriveaxle_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldriveaxle',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='modelengine',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='modelmachine',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='modelsteeringaxle',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='modeltransmission',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='recoverymethod',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='servicecompany',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='typefailure',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='typemaintenance',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
